let noReadObj = {
    "noReadL0" : {percent: cwidget.noReadPercentL0, total: cwidget.noReadTotalL0},
    "noReadL1" : {percent: cwidget.noReadPercentL1, total: cwidget.noReadTotalL1},
    "noReadL2" : {percent: cwidget.noReadPercentL2, total: cwidget.noReadTotalL2},
    "noReadL3" : {percent: cwidget.noReadPercentL3, total: cwidget.noReadTotalL3},
    "noReadL4" : {percent: cwidget.noReadPercentL4, total: cwidget.noReadTotalL4},
    "noReadL5" : {percent: cwidget.noReadPercentL5, total: cwidget.noReadTotalL5},
    "noReadL6" : {percent: cwidget.noReadPercentL6, total: cwidget.noReadTotalL6},
    "noReadL7" : {percent: cwidget.noReadPercentL7, total: cwidget.noReadTotalL7},
    "noReadL8" : {percent: cwidget.noReadPercentL8, total: cwidget.noReadTotalL8},
 }
 let barcodeMismatchObj = {
    "barcodeMismatchL0" : {percent: cwidget.barcodeMismatchPercentL0, total: cwidget.barcodeMismatchTotalL0},
    "barcodeMismatchL1" : {percent: cwidget.barcodeMismatchPercentL1, total: cwidget.barcodeMismatchTotalL1},
    "barcodeMismatchL2" : {percent: cwidget.barcodeMismatchPercentL2, total: cwidget.barcodeMismatchTotalL2},
    "barcodeMismatchL3" : {percent: cwidget.barcodeMismatchPercentL3, total: cwidget.barcodeMismatchTotalL3},
    "barcodeMismatchL4" : {percent: cwidget.barcodeMismatchPercentL4, total: cwidget.barcodeMismatchTotalL4},
    "barcodeMismatchL5" : {percent: cwidget.barcodeMismatchPercentL5, total: cwidget.barcodeMismatchTotalL5},
    "barcodeMismatchL6" : {percent: cwidget.barcodeMismatchPercentL6, total: cwidget.barcodeMismatchTotalL6},
    "barcodeMismatchL7" : {percent: cwidget.barcodeMismatchPercentL7, total: cwidget.barcodeMismatchTotalL7},
    "barcodeMismatchL8" : {percent: cwidget.barcodeMismatchPercentL8, total: cwidget.barcodeMismatchTotalL8},   
 }
 let offsetLidObj = {
    "offsetLidL0" : {percent: cwidget.offsetLidPercentL0, total: cwidget.offsetLidTotalL0},
    "offsetLidL1" : {percent: cwidget.offsetLidPercentL1, total: cwidget.offsetLidTotalL1},
    "offsetLidL2" : {percent: cwidget.offsetLidPercentL2, total: cwidget.offsetLidTotalL2},
    "offsetLidL3" : {percent: cwidget.offsetLidPercentL3, total: cwidget.offsetLidTotalL3},
    "offsetLidL4" : {percent: cwidget.offsetLidPercentL4, total: cwidget.offsetLidTotalL4},
    "offsetLidL5" : {percent: cwidget.offsetLidPercentL5, total: cwidget.offsetLidTotalL5},
    "offsetLidL6" : {percent: cwidget.offsetLidPercentL6, total: cwidget.offsetLidTotalL6},
    "offsetLidL7" : {percent: cwidget.offsetLidPercentL7, total: cwidget.offsetLidTotalL7},
    "offsetLidL8" : {percent: cwidget.offsetLidPercentL8, total: cwidget.offsetLidTotalL8},   
 }
 let tippedPodObj = {
    "tippedPodL0" : {percent: cwidget.tippedPodPercentL0, total: cwidget.tippedPodTotalL0},
    "tippedPodL1" : {percent: cwidget.tippedPodPercentL1, total: cwidget.tippedPodTotalL1},
    "tippedPodL2" : {percent: cwidget.tippedPodPercentL2, total: cwidget.tippedPodTotalL2},
    "tippedPodL3" : {percent: cwidget.tippedPodPercentL3, total: cwidget.tippedPodTotalL3},
    "tippedPodL4" : {percent: cwidget.tippedPodPercentL4, total: cwidget.tippedPodTotalL4},
    "tippedPodL5" : {percent: cwidget.tippedPodPercentL5, total: cwidget.tippedPodTotalL5},
    "tippedPodL6" : {percent: cwidget.tippedPodPercentL6, total: cwidget.tippedPodTotalL6},
    "tippedPodL7" : {percent: cwidget.tippedPodPercentL7, total: cwidget.tippedPodTotalL7},
    "tippedPodL8" : {percent: cwidget.tippedPodPercentL8, total: cwidget.tippedPodTotalL8},   
 }
 let grossDefectObj = {
    "grossDefectL0" : {percent: cwidget.grossDefectPercentL0, total: cwidget.grossDefectTotalL0},
    "grossDefectL1" : {percent: cwidget.grossDefectPercentL1, total: cwidget.grossDefectTotalL1},
    "grossDefectL2" : {percent: cwidget.grossDefectPercentL2, total: cwidget.grossDefectTotalL2},
    "grossDefectL3" : {percent: cwidget.grossDefectPercentL3, total: cwidget.grossDefectTotalL3},
    "grossDefectL4" : {percent: cwidget.grossDefectPercentL4, total: cwidget.grossDefectTotalL4},
    "grossDefectL5" : {percent: cwidget.grossDefectPercentL5, total: cwidget.grossDefectTotalL5},
    "grossDefectL6" : {percent: cwidget.grossDefectPercentL6, total: cwidget.grossDefectTotalL6},
    "grossDefectL7" : {percent: cwidget.grossDefectPercentL7, total: cwidget.grossDefectTotalL7},   
    "grossDefectL8" : {percent: cwidget.grossDefectPercentL8, total: cwidget.grossDefectTotalL8},   
 }
 let partialSealObj = {
    "partialSealL0": {percent: cwidget.partialSealPercentL0, total: cwidget.partialSealTotalL0},
    "partialSealL1": {percent: cwidget.partialSealPercentL1, total: cwidget.partialSealTotalL1},
    "partialSealL2": {percent: cwidget.partialSealPercentL2, total: cwidget.partialSealTotalL2},
    "partialSealL3": {percent: cwidget.partialSealPercentL3, total: cwidget.partialSealTotalL3},
    "partialSealL4": {percent: cwidget.partialSealPercentL4, total: cwidget.partialSealTotalL4},
    "partialSealL5": {percent: cwidget.partialSealPercentL5, total: cwidget.partialSealTotalL5},
    "partialSealL6": {percent: cwidget.partialSealPercentL6, total: cwidget.partialSealTotalL6},
    "partialSealL7": {percent: cwidget.partialSealPercentL7, total: cwidget.partialSealTotalL7},
    "partialSealL8": {percent: cwidget.partialSealPercentL8, total: cwidget.partialSealTotalL8},
 }
 let coffeeInSealObj = {
    "coffeeInSealL0" : {percent: cwidget.coffeeInSealPercentL0, total: cwidget.coffeeInSealTotalL0},
    "coffeeInSealL1" : {percent: cwidget.coffeeInSealPercentL1, total: cwidget.coffeeInSealTotalL1},
    "coffeeInSealL2" : {percent: cwidget.coffeeInSealPercentL2, total: cwidget.coffeeInSealTotalL2},
    "coffeeInSealL3" : {percent: cwidget.coffeeInSealPercentL3, total: cwidget.coffeeInSealTotalL3},
    "coffeeInSealL4" : {percent: cwidget.coffeeInSealPercentL4, total: cwidget.coffeeInSealTotalL4},
    "coffeeInSealL5" : {percent: cwidget.coffeeInSealPercentL5, total: cwidget.coffeeInSealTotalL5},
    "coffeeInSealL6" : {percent: cwidget.coffeeInSealPercentL6, total: cwidget.coffeeInSealTotalL6},
    "coffeeInSealL7" : {percent: cwidget.coffeeInSealPercentL7, total: cwidget.coffeeInSealTotalL7},
    "coffeeInSealL8" : {percent: cwidget.coffeeInSealPercentL8, total: cwidget.coffeeInSealTotalL8},
 }
 let dirtyRimObj = {
    "dirtyRimL0" : {percent: cwidget.dirtyRimPercentL0, total: cwidget.dirtyRimTotalL0},
    "dirtyRimL1" : {percent: cwidget.dirtyRimPercentL1, total: cwidget.dirtyRimTotalL1},
    "dirtyRimL2" : {percent: cwidget.dirtyRimPercentL2, total: cwidget.dirtyRimTotalL2},
    "dirtyRimL3" : {percent: cwidget.dirtyRimPercentL3, total: cwidget.dirtyRimTotalL3},
    "dirtyRimL4" : {percent: cwidget.dirtyRimPercentL4, total: cwidget.dirtyRimTotalL4}, 
    "dirtyRimL5" : {percent: cwidget.dirtyRimPercentL5, total: cwidget.dirtyRimTotalL5},
    "dirtyRimL6" : {percent: cwidget.dirtyRimPercentL6, total: cwidget.dirtyRimTotalL6},
    "dirtyRimL7" : {percent: cwidget.dirtyRimPercentL7, total: cwidget.dirtyRimTotalL7},
    "dirtyRimL8" : {percent: cwidget.dirtyRimPercentL8, total: cwidget.dirtyRimTotalL8},
 }
 let pressDepthObj = {
    "pressDepthL0" : {percent: cwidget.pressDepthPercentL0, total: cwidget.pressDepthTotalL0},
    "pressDepthL1" : {percent: cwidget.pressDepthPercentL1, total: cwidget.pressDepthTotalL1},
    "pressDepthL2" : {percent: cwidget.pressDepthPercentL2, total: cwidget.pressDepthTotalL2},
    "pressDepthL3" : {percent: cwidget.pressDepthPercentL3, total: cwidget.pressDepthTotalL3},
    "pressDepthL4" : {percent: cwidget.pressDepthPercentL4, total: cwidget.pressDepthTotalL4},
    "pressDepthL5" : {percent: cwidget.pressDepthPercentL5, total: cwidget.pressDepthTotalL5},
    "pressDepthL6" : {percent: cwidget.pressDepthPercentL6, total: cwidget.pressDepthTotalL6},
    "pressDepthL7" : {percent: cwidget.pressDepthPercentL7, total: cwidget.pressDepthTotalL7},
    "pressDepthL8" : {percent: cwidget.pressDepthPercentL8, total: cwidget.pressDepthTotalL8},
 }